In [4]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [5]:
X = np.array([[1, 2], [3, 4]])

In [6]:
log_transform =FunctionTransformer(np.log1p)

In [7]:
X_transformed = log_transform.transform(X)

In [8]:
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [9]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [11]:
x = np.array([[1, 2], [3, 4]])

In [12]:
def sakrat_14(x):
    return np.hstack((x, x**2))

In [13]:
custom_transformer = FunctionTransformer(sakrat_14)

In [14]:
x_transformed = custom_transformer.transform(x)

In [15]:
x_transformed

array([[ 1,  2,  1,  4],
       [ 3,  4,  9, 16]])

In [16]:
# Scaling And Normalization

In [17]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [18]:
x = np.array([[1, 2], [3, 4]])

In [19]:
def my_scaling(x):
    return x/np.max(x)

In [20]:
custom_transformer = FunctionTransformer(my_scaling)

In [21]:
x_transformed = custom_transformer.transform(x)

In [22]:
x_transformed

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [23]:
# data cleaning

In [29]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [30]:
x = np.array([[1, 2], [3, np.nan]])

In [31]:
def my_scaling(x):
    x[np.isnan(x)] = 0
    return x

In [32]:
custom_transformer = FunctionTransformer(my_scaling)

In [33]:
x_transformed = custom_transformer.transform(x)

In [34]:
x_transformed

array([[1., 2.],
       [3., 0.]])

In [38]:
import numpy as np
import pandas as pd

In [40]:
df = pd.read_csv('placement.csv')

In [41]:
x = df.drop(columns = ['placed'])

In [42]:
y = df['placed']